[package]
name = "owl-rpc"
version = "0.1.0"
authors = ["Kangsu Kim <pica744@gmail.com>"]

[dependencies]
chrono = { version = "0.4.5", features = ["serde"] }
tarpc = "0.12.0"
tarpc-plugins = "0.4.0"
serde = "1.0.70"
serde_derive = "1.0.70"
