version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ .Branch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ .Branch }}
            - cargo-master
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: cargo-{{ .Branch }}-{{ checksum "Cargo.toml" }}-{{ epoch }}
          paths:
            - "~/.cargo"
            - "target"
