[package]
name = "owl-daemon"
version = "0.1.0"
authors = ["Kangsu Kim <pica744@gmail.com>"]

[dependencies]
owl-exploit = { path = "../owl-exploit" }
diesel = { version = "1.3.2", features = [ "postgres" ] }
dotenv = "0.13.0"
